/// Machine-readable context only; anyhow owns the error, source chain and backtrace.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum ErrorKind {
    #[error("CAPACITY_EXCEEDED")]
    CapacityExceeded,
    #[error("CROSS_CHAIN_ROUTE_UNSUPPORTED")]
    CrossChainRouteUnsupported,
    #[error("INTERNAL_ERROR")]
    InternalError,
    #[error("INVALID_CALLDATA")]
    InvalidCalldata,
    #[error("INVALID_CONFIG")]
    InvalidConfig,
    #[error("INVALID_INPUT")]
    InvalidInput,
    #[error("INVALID_ROUTE")]
    InvalidRoute,
    #[error("INVALID_TAKER")]
    InvalidTaker,
    #[error("METHOD_NOT_ALLOWED")]
    MethodNotAllowed,
    #[error("NATIVE_SELL_UNSUPPORTED")]
    NativeSellUnsupported,
    #[error("NOT_FOUND")]
    NotFound,
    #[error("PAYLOAD_TOO_LARGE")]
    PayloadTooLarge,
    #[error("PROVIDER_UNCONFIGURED")]
    ProviderUnconfigured,
    #[error("QUOTE_EXPIRED")]
    QuoteExpired,
    #[error("ROUTER_NOT_CONFIGURED")]
    RouterNotConfigured,
    #[error("RPC_CALL_FAILED")]
    RpcCallFailed,
    #[error("RPC_CHAIN_MISMATCH")]
    RpcChainMismatch,
    #[error("RPC_INVALID_RESPONSE")]
    RpcInvalidResponse,
    #[error("RPC_METHOD_UNSUPPORTED")]
    RpcMethodUnsupported,
    #[error("RPC_NOT_CONFIGURED")]
    RpcNotConfigured,
    #[error("RPC_TIMEOUT")]
    RpcTimeout,
    #[error("SIMULATION_REVERTED")]
    SimulationReverted,
    #[error("UNEXPECTED_1INCH_CONTRACT")]
    Unexpected1inchContract,
    #[error("UNEXPECTED_TRANSACTION_VALUE")]
    UnexpectedTransactionValue,
    #[error("UNSUPPORTED_CHAIN")]
    UnsupportedChain,
    #[error("UNSUPPORTED_MEDIA_TYPE")]
    UnsupportedMediaType,
    #[error("UPSTREAM_AMOUNT_MISMATCH")]
    UpstreamAmountMismatch,
    #[error("UPSTREAM_AUTH_ERROR")]
    UpstreamAuthError,
    #[error("UPSTREAM_CHAIN_MISMATCH")]
    UpstreamChainMismatch,
    #[error("UPSTREAM_CHAIN_OR_TOKEN_MISMATCH")]
    UpstreamChainOrTokenMismatch,
    #[error("UPSTREAM_EMPTY")]
    UpstreamEmpty,
    #[error("UPSTREAM_HTTP_ERROR")]
    UpstreamHttpError,
    #[error("UPSTREAM_INVALID_JSON")]
    UpstreamInvalidJson,
    #[error("UPSTREAM_INVALID_RESPONSE")]
    UpstreamInvalidResponse,
    #[error("UPSTREAM_MINIMUM_EXCEEDS_QUOTE")]
    UpstreamMinimumExceedsQuote,
    #[error("UPSTREAM_RATE_LIMITED")]
    UpstreamRateLimited,
    #[error("UPSTREAM_RESPONSE_TOO_LARGE")]
    UpstreamResponseTooLarge,
    #[error("UPSTREAM_ROUTER_CHANGED")]
    UpstreamRouterChanged,
    #[error("UPSTREAM_STATE_OVERRIDES_UNSUPPORTED")]
    UpstreamStateOverridesUnsupported,
    #[error("UPSTREAM_TAKER_MISMATCH")]
    UpstreamTakerMismatch,
    #[error("UPSTREAM_TIMEOUT")]
    UpstreamTimeout,
    #[error("UPSTREAM_TOKEN_MISMATCH")]
    UpstreamTokenMismatch,
}

/// The outermost typed classification wins; arbitrary strings never become public codes.
pub fn kind(error: &anyhow::Error) -> ErrorKind {
    error
        .downcast_ref::<ErrorKind>()
        .copied()
        .unwrap_or(ErrorKind::InternalError)
}
